yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('groups/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/',LogoutView.as_view(template_name='users/logged_out.html'),name='logout'),
    path('login/',LoginView.as_view(template_name='users/login.html'),name='login'),
    path('password_change/', PasswordChangeView.as_view(template_name="users/password_change_form.html"),name="password_change"),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),name="password_change_done"),
    path('password_reset/', PasswordResetView.as_view(template_name="users/password_reset_form.html"), name="password_reset"),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name="password_reset_complete")
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    # path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'group',
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='group_post')

    def __str__(self):
        return self.text


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    description = models.TextField()

    def __str__(self):
        return self.title

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):

        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator

from .models import Post, Group, User



def index(request):
    posts_list = Post.objects.order_by('-pub_date')
    paginator = Paginator(posts_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = Post.objects.filter(group=group).order_by('-pub_date')
    paginator = Paginator(posts_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = User.objects.get(username=username)
    posts = user.posts.order_by('-pub_date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'user': user,
        'page_obj': page_obj
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):

    post = get_object_or_404(Post, pk=post_id)

    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)

yatube/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста.
</p>
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block title %}<title>Последние обновления на сайте</title>{% endblock %}
  </head>
  <body>
    {% include 'includes/header.html' %}

    <main>
      <div class="container py-5">
        {% block content %}
        Информация на главной странице будет тут.
        {% endblock %}
      </div>
    </main>

    {% include 'includes/footer.html' %}

  </body>
</html>

yatube/templates/includes/footer.html
    <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
    </footer>

yatube/templates/includes/header.html
{% load static %}
<header>
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
            <!-- ссылка должна вести на главную страницу -->
            <a class="navbar-brand" href="{% url 'posts:index' %}">
                <img src="{% static 'img/logo.png' %}" width="30" height="30"
                     class="d-inline-block align-top" alt="">
                <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
                <span style="color:red">Ya</span>tube
            </a>

            <ul class="nav nav-pills">
                {% with request.resolver_match.view_name as view_name %}
                <li class="nav-item">
                    <a class="nav-link
                     {% if view_name == 'about:author' %}active{% endif %}"
                       href="{% url 'about:author' %}">Об
                        авторе</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link
                     {% if view_name == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
                </li>
               {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="<!--  -->">Новая запись</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light {% if view_name == 'users:password_change' %}active{% endif %}" href="{% url 'users:password_change' %}">Изменить
                        пароль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
                </li>
                <li>
                    Пользователь: {{ user.username }}
                <li>
                    {% else %}
                <li class="nav-item">
                    <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}"
                       href="{% url 'users:signup' %}">Регистрация</a>
                </li>
              {% endif %}
                {% endwith %}
            </ul>
        </div>
    </nav>
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}<title>Записи сообщества {{ group.title }}.</title>{% endblock %}
{% block content %}
<h1>{{ group.title }}</h1>
<p>
    Группа тайных поклонников графа.
</p>
{% for post in page_obj %}
<article>
    <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date }}
        </li>
    </ul>
    <p>
        {{ post.text }}
    </p>
</article>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}

{% include 'posts/includes/paginator.html' %}


{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}<title>Последние обновления на сайте</title>{% endblock %}
{% block content %}
<h1>Последние обновления на сайте</h1>
{% for post in page_obj %}
<article>
    <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:group_list' post.group.slug  %}">все записи группы</a>
</article>

{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}

{% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
<!-- Подключены иконки, стили и заполенены мета теги -->
{% block title %}<title>Пост: {{ post.text|truncatechars:30 }}</title>{% endblock %}

{% block content %}
<div class="row">
    <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <!-- если у поста есть группа -->
            <li class="list-group-item">
                Группа: <!-- Название группы --> {{ post.group }}
                <a href="{% url 'posts:group_list' post.group.slug  %}">
                    все записи группы
                </a>
            </li>
            <li class="list-group-item">
                Автор: <!--Лев Толстой--> {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора: <span>{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author.username %}">
                    все посты пользователя
                </a>
            </li>
        </ul>
    </aside>
    <article class="col-12 col-md-9">
        <p>
            {{ post.text }}
        </p>
    </article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
<!-- Подключены иконки, стили и заполенены мета теги -->
{% block title %}<title>Профайл пользователя {{ user.get_full_name }}</title>{% endblock %}
{% block content %}

<h1>Все посты пользователя {{ user.get_full_name }} </h1>
<h3>Всего постов: {{ page_obj.count }} </h3>
{% for post in page_obj %}
<article>
    <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
            Дата публикации: {{ post.pub_date }}
        </li>
    </ul>
    <p>
        {{ post.text }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
</article>
<a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>

{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}

<!-- Остальные посты. после последнего нет черты -->
<!-- Здесь подключён паджинатор -->
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/users/logged_out.html
{# Это код файла templates/users/logged_out.html #}

{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Войти на сайт
            </div>
            <div class="card-body">
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endif %}

                <form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group row my-3" {% if field.field.required %} aria-required="true" {% else %} aria-required="false" {% endif %}>
                        <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                            {% if field.field.required %}
                            <span class="required text-danger">*</span>
                            {% endif %}
                        </label>
                        <div>
                            {{ field|addclass:'form-control' }}
                            {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help"
                                   class="form-text text-muted">
                                {{ field.help_text|safe }}
                            </small>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Войти
                        </button>
                        <!-- Тест на внимательность. Без переопределения шаблона этого адреса
                        не существует. Нужно что-то делать, иначе все упадет -->
                        <a href="{% url 'users:password_reset' %}"
                           class="btn btn-link">
                            Забыли пароль?
                        </a>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}<title>Пароль изменён</title>{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Пароль изменён
            </div>
            <div class="card-body">
                <p>Пароль изменён успешно</p>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}<title>Изменение пароля</title>{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Изменить пароль
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'users:password_change' %}">
                    {% csrf_token %}
                    <div class="form-group row my-3 p-3">
                        <label for="id_old_password">
                            Старый пароль
                            <span class="required text-danger">*</span>
                        </label>
                        <input type="password" name="old_password" autofocus
                               class="form-control" required
                               id="id_old_password">
                    </div>
                    <div class="form-group row my-3 p-3">
                        <label for="id_new_password1">
                            Новый пароль
                            <span class="required text-danger">*</span>
                        </label>
                        <input type="password" name="new_password1"
                               class="form-control" required
                               id="id_new_password1">
                        <small id="id_new_password1-help"
                               class="form-text text-muted">
                            <ul>
                                <li>Ваш пароль не должен совпадать с вашим
                                    именем или другой персональной информацией
                                    или быть слишком похожим на неё.
                                </li>
                                <li>Ваш пароль должен содержать как минимум 8
                                    символов.
                                </li>
                                <li>Ваш пароль не может быть одним из широко
                                    распространённых паролей.
                                </li>
                                <li>Ваш пароль не может состоять только из
                                    цифр.
                                </li>
                            </ul>
                        </small>
                    </div>
                    <div class="form-group row my-3 p-3">
                        <label for="id_new_password2">
                            Подтверждение нового пароля
                            <span class="required text-danger">*</span>
                        </label>
                        <input type="password" name="new_password2"
                               class="form-control" required
                               id="id_new_password2">
                    </div>
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Изменить пароль
                        </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}<title>Сброс пароля прошёл успешно</title>{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Восстановление пароля завершено
            </div>
            <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="../users/login.html">войти</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html'%}
{% block title %}<title>Новый пароль</title>{% endblock %}
{% block content %}
{% if validlink %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
<!--                <form method="post" action="../users/password_reset_confirm.html">-->
                <form method="post" action="../users/password_reset_confirm.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                    </small>      
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- если использована неправильная ссылка -->
{% else %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Ошибка
              </div>
              <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
{% endif %}
        <!-- конец если использована неправильная ссылка -->
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}<title>Сброс пароля прошёл успешно</title>{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Отправлено письмо
            </div>
            <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для
                    восстановления пароля</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}<title>Сброс пароля</title>{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты,
                под которым вы регистрировались
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'users:password_reset' %}">
                    <input type="hidden" name="csrfmiddlewaretoken" value="{% csrf_token %}">
                    {% csrf_token %}
                    <div class="form-group row my-3 p-3">
                        <label for="id_email">
                            Адрес электронной почты
                            <span class="required text-danger">*</span>
                        </label>
                        <input type="email" name="email" maxlength="254"
                               class="form-control" required id="id_email">
                    </div>
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Сбросить пароль
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}